### ISSUE TITLE
[BUG] Investigate too many fetch requests when doing MCQ Endless and end of Exam mode

### ISSUE THREAD

**Issue by Joecey** [Preclinify/Tickets#63]
## Describe the bug

I noticed when doing MCQ Endless, there is a fetch request being done every time you submit an answer. It looks like it's refetching all the questions again if I am not mistaken. would it be possible to minimise the amount of calls that occur? 

![image](https://github.com/Preclinify/Tickets/assets/84920916/0ab5c879-0f48-4a24-ad24-8675856d48e2)

Just as a note, in the case that it is needed so that the answer a user provides is included in the % distribution, I don't think it's critical to do this

**Comment by highjeans** [comment]
@Joecey I just looked into this. Below is a screenshot of currently what goes through the network from opening the endless page to answering the first question:

<img width="1494" alt="Screenshot 2024-07-10 at 12 12 28" src="https://github.com/Preclinify/Tickets/assets/77588045/39786e83-593e-4dd0-a7b0-32557fdfc2d9">

The first request to "/endless" is to get the first 10 questions. The next request to "/endless" is to update the database with the user's answered option. The last request to "/endless" is for getting the answer counts.

If you want, I can go ahead and make it so that the answer counts are fetched with all of the question data so that all processing of the user's answer choice (except for updating the database) can be done locally.

**Comment by Joecey** [comment]
it would probably be the best if it minimises the amount of requests. If you could draft up a PR for this, that would be great!

**Comment by highjeans** [comment]
For this, should I also minimise the amount of requests in Exam mode? I minimised it in Endless but I believe I will need to do the same in Exam mode.

**Comment by Joecey** [comment]
Oh wow it is the same! Yes if you could limit the requests in exam mode too that would be great!
