### ISSUE TITLE
[BUG] Middleware calls database on each path request

### ISSUE THREAD

**Issue by choco-green** [Preclinify/Tickets#9]
As of 5th May, 2024, we have 36 total registered user, but we have around 300 auth related requests over the last 24 hours. This is because the middleware may call the database to confirm the user are who they say they are.

Refer to supabase - reports - endpoints to view all requests over the last 24 hours.
Refer to supabase - authentication - users to view all registered users.

- Look into if this bug is fixable
- Reduce the amount of api calls to auth whilst assuring no vulnerability is introduced

**Comment by Joecey** [comment]
Following an assessment of our current infrastructure, it appears that we are following Supabase standards when implementing auth. Perhaps our upgrade to the new SSR package has reduced it overall.

A common solution is to user getSession rather than getUser for non-critical areas that you need a user (such as showing specific layouts). **getUser() should always be used for any form of data fetching, mutation and ESPECIALLY in middleware**

As an experiment, I'm going to switch some getUser() to the getSession() method for version 0.0.3 to 0.0.4 to see if we notice any performance improvements (this will only be done server side)

**Comment by Joecey** [comment]
UI stuff is fair game!
![Image](https://github.com/Preclinify/Tickets/assets/84920916/b4177bd1-e20b-46dc-ba09-b282e719d4bc)
